### ISSUE TITLE
Some colour mismatch in Ant-Dracula gnome-shell theme

### ISSUE THREAD

**Issue by milouse** [EliverLara/Ant#24]
Hi!

I don't know if it's on purpose or not, but I found some ant-bloody colors in the ant-dracula theme, mainly in the user menu and actions, as shown in the following captures:

![dracula_usermenu](https://user-images.githubusercontent.com/349239/31879473-c6cbabac-b7dd-11e7-8d88-b15763974647.png)
![dracula_sessionquit](https://user-images.githubusercontent.com/349239/31879471-c685ebee-b7dd-11e7-91eb-e19278ff224b.png)
![dracula_shutdown](https://user-images.githubusercontent.com/349239/31879472-c6a9262c-b7dd-11e7-9a5c-9689e0d56d35.png)

Some label and progress bar use the bloody red colour, when dracula pink may have had the same impact. What do you think about it?

For the two dialog it's not big deal, but it's really annoying (IMHO) for the user submenu and the two progress bar.

[edit] typo

**Comment by milouse** [comment]
BTW, thank you very much for your work, especially with the drucula theme. As I really love pink, It's a pleasure to have a nicely craft dark/pink theme!

**Comment by EliverLara** [comment]
Thank you very much for the observation, I completely forget it.

**Comment by milouse** [comment]
No problem :)

**Comment by EliverLara** [comment]
Fixed in [latest version](https://www.gnome-look.org/p/1099856/).

**Comment by milouse** [comment]
The problem still exists in the dracula shell theme with the last version, as seen on my previous captures :s (Gnome 3.26 on Archlinux)

**Comment by EliverLara** [comment]
The issue was with the Ant-Bloody variant since it was taking the colors of the Ant-Dracula theme, so the Att-Dracula colors did not change.

**Comment by milouse** [comment]
The red progress bar are intended in the Ant-Dracula theme ? Just to be sure.

**Comment by EliverLara** [comment]
Yes, it was made to match the gtk theme, Do you think it should be accent color (pink)?

**Comment by milouse** [comment]
For the logout and shutdown modal, I could understand it uses red color to alert the user on the consequences of these actions. However for the simple progress bar, yes I think the accent color (pink) would be a better choice. I've quickly change the color in the compiled file to show you the difference. I find it more logical, regarding the pink underline effect on the menu button

![screenshot](https://user-images.githubusercontent.com/349239/32381342-bf1e4cd8-c0b2-11e7-9bab-2ecb4f23c108.png)
